
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS payment_types CASCADE;
DROP TABLE IF EXISTS rate_codes CASCADE;
DROP TABLE IF EXISTS location_coordinates CASCADE;
DROP TABLE IF EXISTS weather CASCADE;
DROP TABLE IF EXISTS taxi_trip CASCADE;
DROP TABLE IF EXISTS taxi_trip_features CASCADE;
DROP TABLE IF EXISTS taxi_trip_file_downloads CASCADE;
